### ISSUE TITLE
Support for Vue 3

### ISSUE THREAD

**Issue by murilolopes** [HulkApps/polaris-vue#49]
Hello, 

This package is compatible with Vue 3 and composition API?

**Comment by uttam-hulkapps** [comment]
@murilolopes 

Nop, we are not working on Vue 3 compatibility for now.
Currently we are working on optimising the package size, documentation and getting some more useful components.
We are visioning the Vue 3 Compatibility very soon.

**Comment by MurmeltierS** [comment]
any updates on this?
