### ISSUE TITLE
Scss variables

### ISSUE THREAD

**Issue by murilolopes** [HulkApps/polaris-vue#51]
There is any way to change sass variables without copy and paste from node_modules? Another doubt, can we follow the Shopify colors principles to make changes in styles?

**Comment by uttam-hulkapps** [comment]
@murilolopes 
Currently we are not displaying those variables anywhere in documentation, but we would do it in future update.
And yes we are currently focusing on Shopify colors changes, we may have covered 90% of Shopify's color styles.

Feel free to post any component which is not showing proper color standards with Shopify.

**Comment by uttam-hulkapps** [comment]
Closing this issue.
