### ISSUE TITLE
Storybook not working

### ISSUE THREAD

**Issue by rome2o** [HulkApps/polaris-vue#53]
I just noticed that when I was trying to open the Storybook link it just keeps on loading. I get the following error in the console.

`Uncaught TypeError: Cannot read property 'a' of undefined`

**Comment by uttam-hulkapps** [comment]
Hey @rome2o 

Thank you for heads up.
The documentation site is up now, We were deploying few changes earlier.

Feel free to reopen it if you still have an error with accessing the documentation.

Thanks!
