### ISSUE TITLE
Datatable not working fine

### ISSUE THREAD

**Issue by rome2o** [HulkApps/polaris-vue#54]
Hi there, 

## Bug 1
I was just using the following `PDataTable` component in the system.

https://polaris-vue.hulkapps.com/?path=/docs/lists-tables-data-table--data-table

There seems a bug inside here where if you click the `Filter Options` at the top right, it will put the dropdown in the middle of the screen. 

This behaviour can also be observed here: 
https://polaris-vue.hulkapps.com/?path=/docs/lists-tables-data-table--data-table

![Screen Shot 2021-07-07 at 11 28 29 pm](https://user-images.githubusercontent.com/68844541/124772216-2b95a480-df7f-11eb-8abd-f60e86b6dd74.png)

## Bug 2

I copy pasted the given code in the above storybook, but I get errors on my end. These are as following

```
[Vue warn]: Error in render: "TypeError: value.charAt is not a function"
found in
---> <PBadge>
       <PDataTableCell>
         <PDataTable>
           <App> at src/App.vue
             <Root>
```

```
vue.runtime.esm.js?2b0e:1897 TypeError: value.charAt is not a function
    at variationName (polaris-vue.common.js?fdc2:6987)
    at VueComponent.get (polaris-vue.common.js?fdc2:7026)
```
Due to which I can't see status on, refer to the following screenshot:
    
![Screen Shot 2021-07-08 at 12 00 07 am](https://user-images.githubusercontent.com/68844541/124772546-7adbd500-df7f-11eb-93e3-ad3936eb7c33.png)

**Comment by uttam-hulkapps** [comment]
Hey @rome2o,

For the first bug, it's something conflicting with Storybook's Doc block, we are working on it.
If you open up the same example on new window, it will work fine. Ref: https://polaris-vue.hulkapps.com/iframe.html?id=lists-tables-data-table--data-table&viewMode=story#/

The second bug:
This is the issue of provided data is wrong, I had seen on storybook's example, they haven't displayed the onAction function for action buttons, which is causing issue.
Here is the data example that we are using, I guess this would solve your problem for now.

`sort: {value: 'price', direction: 'ascending'},
    hasPagination: true,
    actions: [
        {
            onAction: (id) => {
                alert('Handle update for id ' + id);
            },
            icon: 'EditMajorMonotone'
        }, {
            onAction: (id) => {
                alert('Handle delete for id ' + id);
            },
            icon: 'DeleteMajorMonotone',
            destructive: true
        }
    ],
    pagination: {
        hasPrevious: true,
        hasNext: true,
        onNext: () => {
            alert('Next');
        },
        onPrevious: () => {
            alert('Previous');
        }
    },
    headings: [{
        content: 'Product',
        value: 'product',
        type: 'text',
        sortable: true,
        width: '30%'
    }, {
        content: 'Price',
        value: 'price',
        type: 'numeric',
        sortable: true,
    }, {
        content: 'SKU Number',
        value: 'sku',
        type: 'numeric',
        sortable: true,
    }, {
        content: 'Net quantity',
        value: 'qty',
        type: 'numeric',
        sortable: true,
    }, {
        content: 'Status',
        value: 'status',
        type: 'string',
        sortable: false,
    }],
    rows: [
        [
            {content: 'Emerald Silk Gown', url: 'https://www.google.com/'},
            '$875.00',
            {content: 121212, status: 'success', progress: 'incomplete'},
            140,
            {
                status: false,
                onAction: ($val) => {
                    console.log($val);
                },
                id: 1
            },
        ],
        [
            {content: 'Mauve Cashmere Scarf', url: 'https://www.google.com/'},
            '$230.00',
            {content: 'A-1234', status: 'success', progress: 'incomplete'},
            2,
            {
                status: true,
                onAction: ($val) => {
                    console.log($val);
                },
                id: 3
            },
        ],
        [
            {content: 'Mauve Cashmere', url: 'https://www.google.com/'},
            '$230.00',
            {content: 'A-1234', status: 'success', progress: 'incomplete'},
            299,
            {
                status: true,
                onAction: ($val) => {
                    console.log($val);
                },
                id: 2
            },
        ],
    ],
    columnContentTypes: [
        'text', 'numeric', 'numeric', 'numeric'
    ],
    totals: [
        '', '', '', 441, '', ''
    ],
    ids: [1, 2, 3]`

**Comment by uttam-hulkapps** [comment]
Closing this issue.
