### ISSUE TITLE
[Suggestion] Modal component, hope to click "Primary Button" to display the loading effect

### ISSUE THREAD

**Issue by PrintNow** [HulkApps/polaris-vue#60]
### Hope to click "Primary Button" to display the loading effect

![image](https://user-images.githubusercontent.com/28396104/127971939-b61a113e-5f37-4463-aacd-0d6d8ab42453.png)

### Like this

![image](https://user-images.githubusercontent.com/28396104/127972261-cee2e364-610d-4d8b-a2ed-980154466b5d.png)

**Comment by saurabh-sali-hulkapps** [comment]
@PrintNow 

Thank you for your suggestion, we will work on it.
