### ISSUE TITLE
[Suggestion] PDataTable components: Hope to provide event trigger

### ISSUE THREAD

**Issue by PrintNow** [HulkApps/polaris-vue#61]
For example, I want to click on these item to execute my custom method in "Vue.js"

![image](https://user-images.githubusercontent.com/28396104/128141170-65753a66-5056-4219-aa29-e4a3680f128f.png)

Current provide configure: 
```js
{
  "content": "2021073012345",
  "url": "javascript:void(0);"
},
```

For example, add an "Action" configuration item here to trigger a custom Vue method
```js
{
  "content": "2021073012345",
  //For example, add an "Action" configuration item here to trigger a custom Vue method
  "onAction": this.someHandle
}
```

### Maybe what I said is not very clear, this is the result I probably want

![image](https://user-images.githubusercontent.com/28396104/128142297-3c7b3788-5e1d-47e9-bf6f-74e4da45c771.png)

**Comment by saurabh-sali-hulkapps** [comment]
@uttam-hulkapps Do we need to add this feature?

**Comment by uttam-hulkapps** [comment]
@saurabh-sali-hulkapps Sure we can think on it.
@PrintNow  Sure we will consider this suggestion on our new releases.
