### ISSUE TITLE
[Bug] PSelect components, if the "valueField" and "textField" parameters are not passed in, an exception will be displayed

### ISSUE THREAD

**Issue by PrintNow** [HulkApps/polaris-vue#63]
This code comes from your document, using this code "PSelect component" can not achieve the expected effect
>  https://polaris-vue.hulkapps.com/?path=/docs/forms-select--select
```vue
<template>
  <div>
    <PSelect
      :disabled="false"
      label="Sort byddd"
      :options='[{"label":"Newest update","value":"newestUpdate"},{"label":"Oldest update","value":"oldestUpdate"},{"label":"Most spent","value":"mostSpent"},{"label":"Most orders","value":"mostOrders","disabled":true},{"label":"Last name A–Z","value":"lastNameAlpha","hidden":true},{"label":"Last name Z–A","value":"lastNameReverseAlpha"}]'
      disabledField=""
      :value="null"
      placeholder="Select"
    />
    <br />
  </div>
</template>
```

![image](https://user-images.githubusercontent.com/28396104/128308015-ff8a11a2-accc-40da-8eb0-06565d0d788f.png)

---

### I thought it was my environmental problem, until I read the source code：[/src/components/PSelect/PSelect.vue#L93](https://github.com/HulkApps/polaris-vue/blob/master/src/components/PSelect/PSelect.vue#L93)

> It seems that the default value is not working

![image](https://user-images.githubusercontent.com/28396104/128307782-09a33e53-08b3-48f1-b38e-f68d3f425deb.png)

### When I manually pass in these parameters, it is work:

```vue
<template>
  <div>
    <PSelect
      :disabled="false"
      label="Sort byddd"
      :options='[{"label":"Newest update","value":"newestUpdate"},{"label":"Oldest update","value":"oldestUpdate"},{"label":"Most spent","value":"mostSpent"},{"label":"Most orders","value":"mostOrders","disabled":true},{"label":"Last name A–Z","value":"lastNameAlpha","hidden":true},{"label":"Last name Z–A","value":"lastNameReverseAlpha"}]'
      disabledField=""
      value-field="label"
      text-field="value"
      :value="null"
      placeholder="Select"
    />
    <br />
  </div>
</template>
```

![image](https://user-images.githubusercontent.com/28396104/128308404-47f6fe92-dbc9-4371-b2b6-0fa91820daf0.png)

**Comment by uttam-hulkapps** [comment]
@PrintNow  
Thank you for reporting the bug here, could you please specify which version you are currently using? 
This issue was raised in 2.3.2 release and we have fixed it on 2.3.3.

Thanks

**Comment by PrintNow** [comment]
@uttam-hulkapps 
Sorry, I am using version 2.3.2, I will update now

**Comment by uttam-hulkapps** [comment]
@PrintNow 

Thank you for confirmation, closing it.
