### ISSUE TITLE
[QUESTION] Connecting PDatatable to Laravel?

### ISSUE THREAD

**Issue by rome2o** [HulkApps/polaris-vue#67]
Hi there,

We've started using this package in our Laravel applications and were wondering if you guys have any thoughts of how should we go connecting PDataTable to the backend inclusive of paginations and other queries? 

Help is much appreciated!

Thanks
Ali

**Comment by saurabh-sali-hulkapps** [comment]
Hi @rome2o,

We have a PPagination component, and you can integrate it with the PDataTable. You can check our components here:- [Polaris-Vue](polaris-vue.hulkapps.com). And if your issue is still unresolved then tell us.

**Comment by uttam-hulkapps** [comment]
Closing this issue as inactive.
