### ISSUE TITLE
How to optimize the packaging volume?

### ISSUE THREAD

**Issue by PrintNow** [HulkApps/polaris-vue#72]
**After packaging, the volume is too large, is there any way to optimize it?**

>The version i use: `"@hulkapps/polaris-vue": "^2.3.7"`
> This is report: https://cdn.nowtime.cc/2021/08/25/938909357.html

![image](https://user-images.githubusercontent.com/28396104/130713813-2c6e3747-200d-43c2-b1c4-3c6be626fba2.png)

file `vue.config.js`:

```js
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

module.exports = {
  productionSourceMap: false,
  devServer: {
    disableHostCheck: true,
  },
  publicPath: process.env.VUE_APP_BASE_URL,
  assetsDir: './assets',
  indexPath: 'index.html',

  configureWebpack: config => {
    let plugins = [
      new UglifyJsPlugin({
        uglifyOptions: {
          compress: {
            warnings: false,
            drop_console: true,
            drop_debugger: true
          },
          output: {
            comments: true
          }
        },
        sourceMap: false,
        parallel: true
      })
    ];

    if (process.env.VUE_APP_build_type === "production") {
      config.plugins = [...config.plugins, ...plugins];
    }
  },
}
```

**Comment by saurabh-sali-hulkapps** [comment]
@PrintNow we working on it.

**Comment by PrintNow** [comment]
@saurabh-sali-hulkapps 
What I mean is that the web page is too big after being built.

**Comment by saurabh-sali-hulkapps** [comment]
@PrintNow We have just released our new version(3.0.2). So check it and rebuild your app.

**Comment by PrintNow** [comment]
@saurabh-sali-hulkapps 
Appreciate your kind assistance! You're awesome.

**Comment by saurabh-sali-hulkapps** [comment]
Thank you!
