### ISSUE TITLE
Drop Zone do not show

### ISSUE THREAD

**Issue by johnnyMxl** [HulkApps/polaris-vue#74]
How to use Drop Zone?

use uploadedFiles

`<PDropZone type="image" :files="[]" :handleOnDrop="onDrop" uploadedFiles>`

Do not display uploaded files

**Comment by saurabh-sali-hulkapps** [comment]
@johnnyMxl Can you share your repository or whole code if you can?

**Comment by johnnyMxl** [comment]
> @johnnyMxl 如果可以，您能分享您的存储库或整个代码吗？

    <PDropZone type="image" :files="[]" :handleOnDrop="onDrop" >
      <template slot="uploadFiles">
        <div></div>
      </template>
    </PDropZone>


    onDrop(files, acceptedFiles) {
      const file = acceptedFiles[0];
      const data = new FormData();
      data.append('file', file);
      axios.post(process.env.VUE_APP_API_URL + "/test", data, {
        headers: {
          'Content-Type': 'multipart/form-data',
        },
      }).then(res => {
        console.log(res);
      }).catch(err => {
        console.log(err);
      });
    },

**Comment by saurabh-sali-hulkapps** [comment]
@johnnyMxl If you want to customize the uploadedFiles feature then you can use slot for that. If you want default configuration then you don't need to add slot.

For a reference you can check below code:- 
`<PDropZone :handleOnDrop="handleDropZoneDrop" :files="images" />
`

Method:-
`
handleDropZoneDrop(files, acceptedFiles, rejectedFiles) {
            acceptedFiles.map((file) => {
            this.images.push(file); // this.images is the data property.
     });
}
`

**Comment by johnnyMxl** [comment]
The problem is solved, thank you very much
