### ISSUE TITLE
Setting Toggle does not support loading spinner

### ISSUE THREAD

**Issue by nguyenanh91** [HulkApps/polaris-vue#75]
The Setting Toggle does not have support for displaying loading spinner when action is taking place.

**Comment by saurabh-sali-hulkapps** [comment]
@nguyenanh91 You can do it manually. Because we are following the Shopify components structure, so we can not add this to our library.

**Comment by nguyenanh91** [comment]
Hi @saurabh-sali-hulkapps 
I have checked the component on Shopify Polaris:
https://polaris.shopify.com/components/actions/setting-toggle/action

They have the "loading" attribute on Setting toggle: https://monosnap.com/file/DLdFggB4ACybFG241Y55bPJ2Jx1fJS

It would be greate if you guys can bring it to the library.
Thanks

**Comment by saurabh-sali-hulkapps** [comment]
@nguyenanh91 Okay we will add it in our next release. Thank you for pointing out this issue.

**Comment by saurabh-sali-hulkapps** [comment]
Released new version
