### ISSUE TITLE
[Suggesstion] I hope `Cleave.js` is integrated into `Text Field` component

### ISSUE THREAD

**Issue by PrintNow** [HulkApps/polaris-vue#77]
Cleave.js has a simple purpose: to help you format input text content automatically.

> GitHub repositories link: https://github.com/nosir/cleave.js
> Use in [VueJs](https://github.com/nosir/cleave.js/blob/master/doc/vue.md)

I hope `Cleave.js` is integrated into `Text Field` component, or `Text Field` component provide extension methods

Thanks :)

**Comment by saurabh-sali-hulkapps** [comment]
@PrintNow Thank you for your suggestion.
