### ISSUE TITLE
[Suggestion] Resource List

### ISSUE THREAD

**Issue by PrintNow** [HulkApps/polaris-vue#78]
![image](https://user-images.githubusercontent.com/28396104/134752394-cda84d57-ceb7-4330-8ba4-e0023d14096c.png)

![image](https://user-images.githubusercontent.com/28396104/134752557-4681fb7e-1b0d-462e-a8a6-8f2cf2f05272.png)

**Comment by saurabh-sali-hulkapps** [comment]
@PrintNow We already knew about this bug and we are working on it too. And thank you for the suggestion.
