### ISSUE TITLE
polaris-vue‘s events had no effect

### ISSUE THREAD

**Issue by chen-ccy** [HulkApps/polaris-vue#87]
Hello, I recently tried to use polaris-vue, found that the element binding event did not take effect, the console reported  errors, please troubleshoot the cause and solve it as soon as possible, thank you

**Comment by saurabh-sali-hulkapps** [comment]
@chen-ccy Can you please share your issue with your code or any repo?

**Comment by chen-ccy** [comment]
At the beginning, I encountered a lot of problems, and after carefully reading the documentation, they were solved. Thank you for introducing such a great product, but hopefully more great features

**Comment by saurabh-sali-hulkapps** [comment]
Thank you for using our library
